name = "ConvolutionOperators"
uuid = "15927181-a1bb-497c-b745-8dbf505c019d"
authors = ["Kristof Cools <krcools@gmail.com> and contributors"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"

[compat]
LinearMaps = "3"
julia = "1"
